### ISSUE TITLE
libsodium.js 0.7.11 does not include crypto_pwhash functions

### ISSUE THREAD

**Issue by marius-wieschollek** [jedisct1/libsodium.js#312]
The crypto_pwhash function is missing after the update from 0.7.10 to 0.7.11.

I have the following code using the function:

```
        let passwordHash = sodium.crypto_pwhash(
            sodium.crypto_box_SEEDBYTES,
            genericHash,
            passwordHashSalt,
            sodium.crypto_pwhash_OPSLIMIT_INTERACTIVE,
            sodium.crypto_pwhash_MEMLIMIT_INTERACTIVE,
            sodium.crypto_pwhash_ALG_DEFAULT
        );
```

This works fine with libsodium-browser 0.7.10, but in 0.7.11 it fails with `TypeError: A().crypto_pwhash is not a function`.

**Comment by jedisct1** [comment]
You need the Sumo version for these functions.

**Comment by marius-wieschollek** [comment]
ok, i see that has changed. but wouldn't it be better to make this a breaking change? Currently npm will ship that update without warning to anyone.

**Comment by cooper667** [comment]
> ok, i see that has changed. but wouldn't it be better to make this a breaking change? Currently npm will ship that update without warning to anyone.

Also the GH readme is accurate, but the NPM readme still states:

`The crypto_pwhash_* function set is included in both versions.`
